# Generated by Django 5.2 on 2025-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
